[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ImperX"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.1.0,<3"
scipy = ">=1.14.1,<2"
tifffile = ">=2024.8.10,<2025"
pillow = ">=10.4.0,<11"
czifile = ">=2019.7.2,<2020"
tqdm = ">=4.66.5,<5"
ipykernel = ">=6.29.5,<7"
matplotlib = ">=3.9.2,<4"
ipywidgets = ">=8.1.5,<9"

[pypi-dependencies]
kyfglib = { path = "./kyfglib", editable = true }
